
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'MiniEye' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks 
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Masonry', '~> 1.0.2'     
  pod 'ZFPlayer', '~> 3.0'
  pod 'Alamofire'
#  pod 'GRDB'

end
